"""Canonical menu content for Bain Al Jusrain, transcribed from the AR trifold brochure.

Every item carries: Arabic name as printed, a Latin transliteration, an English
name, and the price string exactly as printed (slash-separated sizes are kept
verbatim — e.g. "16/22/40.00" is small/medium/large).
"""

# (section_ar, section_en, [(name_ar, translit, name_en, price), ...])
MENU = [
    ("بَراتا جوسرين الخاصة", "Jusrain Special Paratha", [
        ("فرانسيسكو", "Fransisco", "Francisco paratha roll", "7.00"),
        ("كيما", "Keema", "Minced meat paratha", "4.50"),
        ("بيض وجبنة", "Baid wa Jibna", "Egg and cheese paratha", "4.50"),
        ("جبنة", "Jibna", "Cheese paratha", "3.00"),
        ("بيض", "Baid", "Egg paratha", "4.00"),
        ("أومان شيبس جبنة", "Oman Chips Jibna", "Oman chips and cheese paratha", "4.00"),
        ("بيض شيبس أومان جبنة", "Baid Chips Oman Jibna", "Egg, Oman chips and cheese paratha", "5.50"),
        ("لحم بقري", "Lahm Baqari", "Beef paratha", "6.00"),
        ("دجاج تشيلي", "Dajaj Chilli", "Chilli chicken paratha", "6.00"),
        ("دجاج", "Dajaj", "Chicken paratha", "5.50"),
        ("نوتيلا", "Nutella", "Nutella paratha", "4.00"),
        ("عسل", "Asal", "Honey paratha", "4.00"),
        ("شكشوكة", "Shakshuka", "Shakshuka paratha", "5.00"),
        ("شكشوكة جبنة", "Shakshuka Jibna", "Shakshuka and cheese paratha", "6.00"),
    ]),
    ("المشروبات الساخنة", "Hot Drinks", [
        ("شاي كرك", "Shai Karak", "Karak tea", "1.50 / 3.00"),
        ("شاي حليب طازج", "Shai Haleeb Tazij", "Fresh milk tea", "2.50 / 5.00"),
        ("شاي أسود", "Shai Aswad", "Black tea", "1.50 / 3.00"),
        ("شاي أخضر", "Shai Akhdar", "Green tea", "1.50 / 3.00"),
        ("قهوة", "Qahwa", "Coffee", "2.50 / 5.00"),
        ("شاي زعتر", "Shai Zaatar", "Thyme tea", "3 / 6.00"),
        ("شاي زعفران", "Shai Zaafaran", "Saffron tea", "3.50 / 7.00"),
    ]),
    ("الشوربات الخاصة", "Special Soups", [
        ("شوربة مأكولات بحرية", "Shorbat Makoolat Bahriya", "Seafood soup", "10.00"),
        ("شوربة كريمة فطر", "Shorbat Kareemat Fitr", "Cream of mushroom soup", "10.00"),
        ("شوربة كريمة دجاج", "Shorbat Kareemat Dajaj", "Cream of chicken soup", "10.00"),
        ("شوربة دجاج وفطر", "Shorbat Dajaj wa Fitr", "Chicken and mushroom soup", "10.00"),
        ("شوربة دجاج حارة وحامضة", "Shorbat Dajaj Harra wa Hamda", "Hot and sour chicken soup", "10.00"),
        ("شوربة لحم غنم حارة وحامضة", "Shorbat Lahm Ghanam Harra wa Hamda", "Hot and sour mutton soup", "10.00"),
        ("شوربة طماطم", "Shorbat Tamatim", "Tomato soup", "10.00"),
        ("شوربة نعناع أخضر", "Shorbat Naanaa Akhdar", "Green mint soup", "10.00"),
        ("شوربة كريمة خضار", "Shorbat Kareemat Khudar", "Cream of vegetable soup", "10.00"),
        ("شوربة ذرة حلوة بالخضار", "Shorbat Thura Hilwa bil Khudar", "Sweet corn and vegetable soup", "10.00"),
        ("شوربة مانشاو خضار", "Shorbat Manchow Khudar", "Vegetable manchow soup", "10.00"),
    ]),
    ("أطباق الأرز", "Rice Dishes", [
        ("أرز أبيض", "Aruz Abyad", "Plain white rice", "6.00"),
        ("أرز برياني", "Aruz Biryani", "Biryani rice", "6.00"),
        ("أرز بلاو", "Aruz Pulao", "Pulao rice", "7.00"),
    ]),
    ("وجبات الأرز الكومبو", "Rice Combo Meals", [
        ("وجبة موتا", "Wajbat Mota", "Mota combo meal", "10.00"),
        ("وجبة باريك", "Wajbat Bareek", "Bareek combo meal", "10.00"),
    ]),
    ("الخبز", "Bread", [
        ("روتي", "Roti", "Roti", "1.50"),
        ("براتا", "Paratha", "Paratha", "1.50"),
        ("شاباتي", "Chapati", "Chapati", "1.50"),
    ]),
    ("برياني جوسرين الخاص", "Jusrain Special Biryani", [
        ("برياني دجاج", "Biryani Dajaj", "Chicken biryani", "13.00"),
        ("نصف برياني دجاج", "Nusf Biryani Dajaj", "Half chicken biryani", "20.00"),
        ("برياني دجاج دم", "Biryani Dajaj Dum", "Chicken dum biryani", "14.00"),
        ("نصف برياني دجاج دوم", "Nusf Biryani Dajaj Dum", "Half chicken dum biryani", "22.00"),
        ("برياني لحم بقري", "Biryani Lahm Baqari", "Beef biryani", "16.00"),
        ("برياني بيض", "Biryani Baid", "Egg biryani", "12.00"),
        ("برياني خضار", "Biryani Khudar", "Vegetable biryani", "12.00"),
        ("برياني دجاج 65", "Biryani Dajaj 65", "Chicken 65 biryani", "25.00"),
        ("برياني لحم غنم نمكين", "Biryani Lahm Ghanam Namkeen", "Namkeen mutton biryani", "25.00"),
        ("برياني الفحم كامل", "Biryani al-Fahm Kamil", "Full charcoal biryani", "50.00"),
        ("نصف برياني بالفحم", "Nusf Biryani bil Fahm", "Half charcoal biryani", "25.00"),
        ("برياني حيدرآبادي", "Biryani Hyderabadi", "Hyderabadi biryani", "14.00"),
        ("برياني سمك", "Biryani Samak", "Fish biryani", "SEASONAL"),
        ("برياني لحم غنم", "Biryani Lahm Ghanam", "Mutton biryani", "19.00"),
    ]),
    ("أطباق اللحم البقري الخاصة", "Special Beef Dishes", [
        ("لحم بقري مقلي", "Lahm Baqari Maqli", "Beef fry", "13.00"),
        ("لحم بقري ماسالا", "Lahm Baqari Masala", "Beef masala", "13.00"),
        ("لحم بقري روست", "Lahm Baqari Roast", "Beef roast", "20.00"),
    ]),
    ("أطباق لحم الغنم الخاصة", "Special Mutton Dishes", [
        ("كاداي لحم بقري", "Kadai Lahm Baqari", "Beef kadai", "16.00"),
        ("لحم غنم نمكين", "Lahm Ghanam Namkeen", "Namkeen mutton", "23.00"),
        ("كاداي لحم غنم", "Kadai Lahm Ghanam", "Mutton kadai", "17.00"),
        ("لحم غنم ماسالا", "Lahm Ghanam Masala", "Mutton masala", "14.00"),
        ("لحم غنم روست", "Lahm Ghanam Roast", "Mutton roast", "20.00"),
        ("كبدة غنم", "Kabdat Ghanam", "Mutton liver", "13.00"),
        ("لحم غنم بالبطاطس", "Lahm Ghanam bil Bataties", "Mutton with potato", "17.00"),
        ("لحم غنم بالعدس", "Lahm Ghanam bil Adas", "Mutton with lentils", "17.00"),
        ("لحم غنم بالبامية", "Lahm Ghanam bil Bamya", "Mutton with okra", "17.00"),
    ]),
    ("بلاو وكبسة جوسرين الخاصة", "Jusrain Special Pulao and Kabsa", [
        ("بلاو لحم بقري", "Pulao Lahm Baqari", "Beef pulao", "17.00"),
        ("بلاو دجاج", "Pulao Dajaj", "Chicken pulao", "14.00"),
        ("بلاو لحم غنم نمكين", "Pulao Lahm Ghanam Namkeen", "Namkeen mutton pulao", "25.00"),
        ("بلاو لحم غنم", "Pulao Lahm Ghanam", "Mutton pulao", "20.00"),
    ]),
    ("أطباق الدجاج الخاصة", "Special Chicken Dishes", [
        ("دجاج 65", "Dajaj 65", "Chicken 65", "16.00 / 20.00 / 25.00"),
        ("دجاج تشيلي صيني", "Dajaj Chilli Sini", "Chinese chilli chicken", "16.00"),
        ("دجاج ماسالا", "Dajaj Masala", "Chicken masala", "12.00"),
        ("صحن فرانسيسكو", "Sahn Fransisco", "Francisco platter (regular)", "20.00"),
        ("صحن فرانسيسكو كبير", "Sahn Fransisco Kabeer", "Francisco platter (large)", "30.00"),
        ("دجاج بالزبدة كامل", "Dajaj bil Zubda Kamil", "Full butter chicken", "20.00"),
        ("نصف دجاجة بالزبدة", "Nusf Dajaja bil Zubda", "Half butter chicken", "16.00"),
        ("كاداي دجاج", "Kadai Dajaj", "Chicken kadai", "13.00"),
        ("تشيكن تشوكا", "Chicken Chukka", "Chicken chukka", "13.00"),
        ("دجاج تشيلي", "Dajaj Chilli", "Chilli chicken", "13.00"),
    ]),
    ("أطباق الفحم الخاصة", "Special Charcoal Grills", [
        ("فحم فلفل أخضر حار", "Fahm Filfil Akhdar Har", "Hot green pepper charcoal grill", "16/22/40.00"),
        ("فحم إيري بوري", "Fahm Eeri Boori", "Eeri Boori charcoal grill", "16/22/40.00"),
        ("شيش كباب دجاج", "Shish Kabab Dajaj", "Chicken shish kebab", "18.00"),
        ("شيش كباب لحم غنم", "Shish Kabab Lahm Ghanam", "Mutton shish kebab", "20.00"),
        ("فحم فلفل أسود", "Fahm Filfil Aswad", "Black pepper charcoal grill", "16/22/40.00"),
        ("فحم عادي", "Fahm Aadi", "Classic charcoal grill", "16/22/40.00"),
        ("تكا دجاج", "Tikka Dajaj", "Chicken tikka", "18.00"),
        ("ملاي تكا", "Malai Tikka", "Malai tikka", "20.00"),
    ]),
    ("السلطات الخاصة", "Special Salads", [
        ("سلطة تكا دجاج", "Salatat Tikka Dajaj", "Chicken tikka salad", "12.00"),
        ("سلطة عربية", "Salata Arabiya", "Arabic salad", "10.00"),
        ("سلطة خضراء", "Salata Khadra", "Green salad", "2/5/10.00"),
        ("سلطة عربية (صغيرة)", "Salata Arabiya (Saghira)", "Arabic salad (small)", "5.00"),
    ]),
    ("أطباق السمك الخاصة", "Special Fish Dishes", [
        ("شعري مقلي", "Shaari Maqli", "Fried sheri (emperor fish)", "APS"),
        ("روبيان مقلي", "Rubyan Maqli", "Fried prawns", "20.00"),
        ("هامور فحم", "Hamour Fahm", "Charcoal-grilled hammour", "APS"),
        ("روبيان ماسالا", "Rubyan Masala", "Prawn masala", "20.00"),
        ("سمك الملك مقلي", "Samak al-Malik Maqli", "Fried king fish", "APS"),
        ("هامور مقلي", "Hamour Maqli", "Fried hammour", "APS"),
    ]),
    ("أطباق الفطور الخاصة", "Special Breakfast Dishes", [
        ("عدس شانا", "Adas Chana", "Lentil chana", "6/8/12.00"),
        ("بيض بورجي", "Baid Burji", "Egg burji", "6/9/12.00"),
        ("حمص ماسالا", "Hummus Masala", "Chana masala", "6/8/12.00"),
        ("بامية", "Bamya", "Okra", "6/8/12.00"),
        ("دوسا سيت", "Dosa Set", "Dosa set", "6.00"),
        ("عدس مقلي", "Adas Maqli", "Fried lentils", "6/8/12.00"),
        ("كيما", "Keema", "Keema", "6/8/12.00"),
        ("فول", "Foul", "Foul", "10.00"),
        ("بيض روست", "Baid Roast", "Egg roast", "6/9/12.00"),
        ("بطاطس بالسبانخ", "Bataties bil Sabanikh", "Potato with spinach", "6/8/12.00"),
    ]),
]

RESTAURANT = {
    "name_en": "Bain Al Jusrain Restaurant",
    "name_ar": "مطعم بين الجسرين",
    "since": "2000",
    "phone": "+971 25 588 981",
    "whatsapp": "+971 54 449 3105",
    "address_ar": "بالقرب من محطة البنزين، منطقة جسرين، ربدان المقطع، أبو ظبي - الإمارات",
    "address_en": "Near the petrol station, Jusrain area, Rabdan Al Maqta, Abu Dhabi - UAE",
    "delivery": "KeeTa home delivery",
    "currency": "AED",
}
